
- name: Update cache
  apt: update_cache=yes cache_valid_time=43200 #12 hours

- name: Install deps
  apt: pkg={{ item }} state=present
  with_items:
    - ffmpeg
    - v4l-utils
    - libmariadbclient18
    - libpq5
    - python-pip
    - python-dev
    - curl
    - libssl-dev
    - libcurl4-openssl-dev
    - libjpeg-dev
    - libz-dev
    
- name: download and install current version of motion
  apt:
    deb: - https://github.com/Motion-Project/motion/releases/download/release-4.1.1/pi_stretch_motion_4.1.1-1_armhf.deb


